"""Initial migration.

Revision ID: 75ca035bc5a8
Revises: a6f6753a097f
Create Date: 2024-10-17 19:53:03.837717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ca035bc5a8'
down_revision = 'a6f6753a097f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('date_hired', sa.DateTime(), nullable=True),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
